select countrycode3 as country3, countrynameofficial as countryname, tt.* from dbo.t_country, (select isnull(t23.CountryCode, ct23.country2) as country2, 
				isnull(t23.AccessWaterYear, ct23.year) as year, t23.AccessWater, ct23.AccessCreditDataDepth, ct23.AccessCreditDataLegal, ct23.AccessCreditAgg, ct23.BusStartUpDataDays, ct23.BusStartUpDataCost, ct23.BusStartUpAgg, ct23.CHData, ct23.CivLibData, ct23.ConCorData, ct23.EducExpDataPOST, ct23.EducExpDataUNESCO, ct23.EducExpAgg, ct23.FisPolData, ct23.FisPolAgg, ct23.FreedomInfoDataFreePress, ct23.FreedomInfoDataFOIA, ct23.FreedomInfoDataInterTools, ct23.FreedomInfoDataPolyNet, ct23.FreedomInfoAgg, ct23.GenderEconData, ct23.GirlsPrimData, ct23.GirlsSecData, ct23.GovtEffData, ct23.HealthData, ct23.ImmunDataDPT3, ct23.ImmunDataMCV, ct23.ImmunAgg, ct23.InflData, ct23.LRADataIFAD, ct23.LRADataIFCTime, ct23.LRADataIFCCost, ct23.LRAAgg, ct23.NRMData, ct23.PolRigData, ct23.RegQualityData, ct23.RuleLawData, ct23.TradeData, ct23.ChildMortality, ct23.AccessSanitation from (select isnull(t22.CountryCode, ct22.country2) as country2, 
				isnull(t22.AccessSanitationYear, ct22.year) as year, t22.AccessSanitation, ct22.AccessCreditDataDepth, ct22.AccessCreditDataLegal, ct22.AccessCreditAgg, ct22.BusStartUpDataDays, ct22.BusStartUpDataCost, ct22.BusStartUpAgg, ct22.CHData, ct22.CivLibData, ct22.ConCorData, ct22.EducExpDataPOST, ct22.EducExpDataUNESCO, ct22.EducExpAgg, ct22.FisPolData, ct22.FisPolAgg, ct22.FreedomInfoDataFreePress, ct22.FreedomInfoDataFOIA, ct22.FreedomInfoDataInterTools, ct22.FreedomInfoDataPolyNet, ct22.FreedomInfoAgg, ct22.GenderEconData, ct22.GirlsPrimData, ct22.GirlsSecData, ct22.GovtEffData, ct22.HealthData, ct22.ImmunDataDPT3, ct22.ImmunDataMCV, ct22.ImmunAgg, ct22.InflData, ct22.LRADataIFAD, ct22.LRADataIFCTime, ct22.LRADataIFCCost, ct22.LRAAgg, ct22.NRMData, ct22.PolRigData, ct22.RegQualityData, ct22.RuleLawData, ct22.TradeData, ct22.ChildMortality from (select isnull(t21.CountryCode, ct21.country2) as country2, 
				isnull(t21.ChildMortalityYear, ct21.year) as year, t21.ChildMortality, ct21.AccessCreditDataDepth, ct21.AccessCreditDataLegal, ct21.AccessCreditAgg, ct21.BusStartUpDataDays, ct21.BusStartUpDataCost, ct21.BusStartUpAgg, ct21.CHData, ct21.CivLibData, ct21.ConCorData, ct21.EducExpDataPOST, ct21.EducExpDataUNESCO, ct21.EducExpAgg, ct21.FisPolData, ct21.FisPolAgg, ct21.FreedomInfoDataFreePress, ct21.FreedomInfoDataFOIA, ct21.FreedomInfoDataInterTools, ct21.FreedomInfoDataPolyNet, ct21.FreedomInfoAgg, ct21.GenderEconData, ct21.GirlsPrimData, ct21.GirlsSecData, ct21.GovtEffData, ct21.HealthData, ct21.ImmunDataDPT3, ct21.ImmunDataMCV, ct21.ImmunAgg, ct21.InflData, ct21.LRADataIFAD, ct21.LRADataIFCTime, ct21.LRADataIFCCost, ct21.LRAAgg, ct21.NRMData, ct21.PolRigData, ct21.RegQualityData, ct21.RuleLawData, ct21.TradeData from (select isnull(t20.TradeCountryCode, ct20.country2) as country2, 
				isnull(t20.TradeYear, ct20.year) as year, t20.TradeData, ct20.AccessCreditDataDepth, ct20.AccessCreditDataLegal, ct20.AccessCreditAgg, ct20.BusStartUpDataDays, ct20.BusStartUpDataCost, ct20.BusStartUpAgg, ct20.CHData, ct20.CivLibData, ct20.ConCorData, ct20.EducExpDataPOST, ct20.EducExpDataUNESCO, ct20.EducExpAgg, ct20.FisPolData, ct20.FisPolAgg, ct20.FreedomInfoDataFreePress, ct20.FreedomInfoDataFOIA, ct20.FreedomInfoDataInterTools, ct20.FreedomInfoDataPolyNet, ct20.FreedomInfoAgg, ct20.GenderEconData, ct20.GirlsPrimData, ct20.GirlsSecData, ct20.GovtEffData, ct20.HealthData, ct20.ImmunDataDPT3, ct20.ImmunDataMCV, ct20.ImmunAgg, ct20.InflData, ct20.LRADataIFAD, ct20.LRADataIFCTime, ct20.LRADataIFCCost, ct20.LRAAgg, ct20.NRMData, ct20.PolRigData, ct20.RegQualityData, ct20.RuleLawData from (select isnull(t19.RuleLawCountryCode, ct19.country2) as country2, 
				isnull(t19.RuleLawYear, ct19.year) as year, t19.RuleLawData, ct19.AccessCreditDataDepth, ct19.AccessCreditDataLegal, ct19.AccessCreditAgg, ct19.BusStartUpDataDays, ct19.BusStartUpDataCost, ct19.BusStartUpAgg, ct19.CHData, ct19.CivLibData, ct19.ConCorData, ct19.EducExpDataPOST, ct19.EducExpDataUNESCO, ct19.EducExpAgg, ct19.FisPolData, ct19.FisPolAgg, ct19.FreedomInfoDataFreePress, ct19.FreedomInfoDataFOIA, ct19.FreedomInfoDataInterTools, ct19.FreedomInfoDataPolyNet, ct19.FreedomInfoAgg, ct19.GenderEconData, ct19.GirlsPrimData, ct19.GirlsSecData, ct19.GovtEffData, ct19.HealthData, ct19.ImmunDataDPT3, ct19.ImmunDataMCV, ct19.ImmunAgg, ct19.InflData, ct19.LRADataIFAD, ct19.LRADataIFCTime, ct19.LRADataIFCCost, ct19.LRAAgg, ct19.NRMData, ct19.PolRigData, ct19.RegQualityData from (select isnull(t18.RegQualityCountryCode, ct18.country2) as country2, 
				isnull(t18.RegQualityYear, ct18.year) as year, t18.RegQualityData, ct18.AccessCreditDataDepth, ct18.AccessCreditDataLegal, ct18.AccessCreditAgg, ct18.BusStartUpDataDays, ct18.BusStartUpDataCost, ct18.BusStartUpAgg, ct18.CHData, ct18.CivLibData, ct18.ConCorData, ct18.EducExpDataPOST, ct18.EducExpDataUNESCO, ct18.EducExpAgg, ct18.FisPolData, ct18.FisPolAgg, ct18.FreedomInfoDataFreePress, ct18.FreedomInfoDataFOIA, ct18.FreedomInfoDataInterTools, ct18.FreedomInfoDataPolyNet, ct18.FreedomInfoAgg, ct18.GenderEconData, ct18.GirlsPrimData, ct18.GirlsSecData, ct18.GovtEffData, ct18.HealthData, ct18.ImmunDataDPT3, ct18.ImmunDataMCV, ct18.ImmunAgg, ct18.InflData, ct18.LRADataIFAD, ct18.LRADataIFCTime, ct18.LRADataIFCCost, ct18.LRAAgg, ct18.NRMData, ct18.PolRigData from (select isnull(t17.PolRigCountryCode, ct17.country2) as country2, 
				isnull(t17.PolRigYear, ct17.year) as year, t17.PolRigData, ct17.AccessCreditDataDepth, ct17.AccessCreditDataLegal, ct17.AccessCreditAgg, ct17.BusStartUpDataDays, ct17.BusStartUpDataCost, ct17.BusStartUpAgg, ct17.CHData, ct17.CivLibData, ct17.ConCorData, ct17.EducExpDataPOST, ct17.EducExpDataUNESCO, ct17.EducExpAgg, ct17.FisPolData, ct17.FisPolAgg, ct17.FreedomInfoDataFreePress, ct17.FreedomInfoDataFOIA, ct17.FreedomInfoDataInterTools, ct17.FreedomInfoDataPolyNet, ct17.FreedomInfoAgg, ct17.GenderEconData, ct17.GirlsPrimData, ct17.GirlsSecData, ct17.GovtEffData, ct17.HealthData, ct17.ImmunDataDPT3, ct17.ImmunDataMCV, ct17.ImmunAgg, ct17.InflData, ct17.LRADataIFAD, ct17.LRADataIFCTime, ct17.LRADataIFCCost, ct17.LRAAgg, ct17.NRMData from (select isnull(t16.NRMCountryCode, ct16.country2) as country2, 
				isnull(t16.NRMYear, ct16.year) as year, t16.NRMData, ct16.AccessCreditDataDepth, ct16.AccessCreditDataLegal, ct16.AccessCreditAgg, ct16.BusStartUpDataDays, ct16.BusStartUpDataCost, ct16.BusStartUpAgg, ct16.CHData, ct16.CivLibData, ct16.ConCorData, ct16.EducExpDataPOST, ct16.EducExpDataUNESCO, ct16.EducExpAgg, ct16.FisPolData, ct16.FisPolAgg, ct16.FreedomInfoDataFreePress, ct16.FreedomInfoDataFOIA, ct16.FreedomInfoDataInterTools, ct16.FreedomInfoDataPolyNet, ct16.FreedomInfoAgg, ct16.GenderEconData, ct16.GirlsPrimData, ct16.GirlsSecData, ct16.GovtEffData, ct16.HealthData, ct16.ImmunDataDPT3, ct16.ImmunDataMCV, ct16.ImmunAgg, ct16.InflData, ct16.LRADataIFAD, ct16.LRADataIFCTime, ct16.LRADataIFCCost, ct16.LRAAgg from (select isnull(t15.LRACountryCode, ct15.country2) as country2, 
				isnull(t15.LRAYear, ct15.year) as year, t15.LRADataIFAD, t15.LRADataIFCTime, t15.LRADataIFCCost, t15.LRAAgg, ct15.AccessCreditDataDepth, ct15.AccessCreditDataLegal, ct15.AccessCreditAgg, ct15.BusStartUpDataDays, ct15.BusStartUpDataCost, ct15.BusStartUpAgg, ct15.CHData, ct15.CivLibData, ct15.ConCorData, ct15.EducExpDataPOST, ct15.EducExpDataUNESCO, ct15.EducExpAgg, ct15.FisPolData, ct15.FisPolAgg, ct15.FreedomInfoDataFreePress, ct15.FreedomInfoDataFOIA, ct15.FreedomInfoDataInterTools, ct15.FreedomInfoDataPolyNet, ct15.FreedomInfoAgg, ct15.GenderEconData, ct15.GirlsPrimData, ct15.GirlsSecData, ct15.GovtEffData, ct15.HealthData, ct15.ImmunDataDPT3, ct15.ImmunDataMCV, ct15.ImmunAgg, ct15.InflData from (select isnull(t14.InflCountryCode, ct14.country2) as country2, 
				isnull(t14.InflYear, ct14.year) as year, t14.InflData, ct14.AccessCreditDataDepth, ct14.AccessCreditDataLegal, ct14.AccessCreditAgg, ct14.BusStartUpDataDays, ct14.BusStartUpDataCost, ct14.BusStartUpAgg, ct14.CHData, ct14.CivLibData, ct14.ConCorData, ct14.EducExpDataPOST, ct14.EducExpDataUNESCO, ct14.EducExpAgg, ct14.FisPolData, ct14.FisPolAgg, ct14.FreedomInfoDataFreePress, ct14.FreedomInfoDataFOIA, ct14.FreedomInfoDataInterTools, ct14.FreedomInfoDataPolyNet, ct14.FreedomInfoAgg, ct14.GenderEconData, ct14.GirlsPrimData, ct14.GirlsSecData, ct14.GovtEffData, ct14.HealthData, ct14.ImmunDataDPT3, ct14.ImmunDataMCV, ct14.ImmunAgg from (select isnull(t13.ImmunCountryCode, ct13.country2) as country2, 
				isnull(t13.ImmunYear, ct13.year) as year, t13.ImmunDataDPT3, t13.ImmunDataMCV, t13.ImmunAgg, ct13.AccessCreditDataDepth, ct13.AccessCreditDataLegal, ct13.AccessCreditAgg, ct13.BusStartUpDataDays, ct13.BusStartUpDataCost, ct13.BusStartUpAgg, ct13.CHData, ct13.CivLibData, ct13.ConCorData, ct13.EducExpDataPOST, ct13.EducExpDataUNESCO, ct13.EducExpAgg, ct13.FisPolData, ct13.FisPolAgg, ct13.FreedomInfoDataFreePress, ct13.FreedomInfoDataFOIA, ct13.FreedomInfoDataInterTools, ct13.FreedomInfoDataPolyNet, ct13.FreedomInfoAgg, ct13.GenderEconData, ct13.GirlsPrimData, ct13.GirlsSecData, ct13.GovtEffData, ct13.HealthData from (select isnull(t12.HealthCountryCode, ct12.country2) as country2, 
				isnull(t12.HealthYear, ct12.year) as year, t12.HealthData, ct12.AccessCreditDataDepth, ct12.AccessCreditDataLegal, ct12.AccessCreditAgg, ct12.BusStartUpDataDays, ct12.BusStartUpDataCost, ct12.BusStartUpAgg, ct12.CHData, ct12.CivLibData, ct12.ConCorData, ct12.EducExpDataPOST, ct12.EducExpDataUNESCO, ct12.EducExpAgg, ct12.FisPolData, ct12.FisPolAgg, ct12.FreedomInfoDataFreePress, ct12.FreedomInfoDataFOIA, ct12.FreedomInfoDataInterTools, ct12.FreedomInfoDataPolyNet, ct12.FreedomInfoAgg, ct12.GenderEconData, ct12.GirlsPrimData, ct12.GirlsSecData, ct12.GovtEffData from (select isnull(t11.GovtEffCountryCode, ct11.country2) as country2, 
				isnull(t11.GovtEffYear, ct11.year) as year, t11.GovtEffData, ct11.AccessCreditDataDepth, ct11.AccessCreditDataLegal, ct11.AccessCreditAgg, ct11.BusStartUpDataDays, ct11.BusStartUpDataCost, ct11.BusStartUpAgg, ct11.CHData, ct11.CivLibData, ct11.ConCorData, ct11.EducExpDataPOST, ct11.EducExpDataUNESCO, ct11.EducExpAgg, ct11.FisPolData, ct11.FisPolAgg, ct11.FreedomInfoDataFreePress, ct11.FreedomInfoDataFOIA, ct11.FreedomInfoDataInterTools, ct11.FreedomInfoDataPolyNet, ct11.FreedomInfoAgg, ct11.GenderEconData, ct11.GirlsPrimData, ct11.GirlsSecData from (select isnull(t10.GirlsSecCountryCode, ct10.country2) as country2, 
				isnull(t10.GirlsSecYear, ct10.year) as year, t10.GirlsSecData, ct10.AccessCreditDataDepth, ct10.AccessCreditDataLegal, ct10.AccessCreditAgg, ct10.BusStartUpDataDays, ct10.BusStartUpDataCost, ct10.BusStartUpAgg, ct10.CHData, ct10.CivLibData, ct10.ConCorData, ct10.EducExpDataPOST, ct10.EducExpDataUNESCO, ct10.EducExpAgg, ct10.FisPolData, ct10.FisPolAgg, ct10.FreedomInfoDataFreePress, ct10.FreedomInfoDataFOIA, ct10.FreedomInfoDataInterTools, ct10.FreedomInfoDataPolyNet, ct10.FreedomInfoAgg, ct10.GenderEconData, ct10.GirlsPrimData from (select isnull(t9.GirlsPrimCountryCode, ct9.country2) as country2, 
				isnull(t9.GirlsPrimYear, ct9.year) as year, t9.GirlsPrimData, ct9.AccessCreditDataDepth, ct9.AccessCreditDataLegal, ct9.AccessCreditAgg, ct9.BusStartUpDataDays, ct9.BusStartUpDataCost, ct9.BusStartUpAgg, ct9.CHData, ct9.CivLibData, ct9.ConCorData, ct9.EducExpDataPOST, ct9.EducExpDataUNESCO, ct9.EducExpAgg, ct9.FisPolData, ct9.FisPolAgg, ct9.FreedomInfoDataFreePress, ct9.FreedomInfoDataFOIA, ct9.FreedomInfoDataInterTools, ct9.FreedomInfoDataPolyNet, ct9.FreedomInfoAgg, ct9.GenderEconData from (select isnull(t8.GenderEconCountryCode, ct8.country2) as country2, 
				isnull(t8.GenderEconYear, ct8.year) as year, t8.GenderEconData, ct8.AccessCreditDataDepth, ct8.AccessCreditDataLegal, ct8.AccessCreditAgg, ct8.BusStartUpDataDays, ct8.BusStartUpDataCost, ct8.BusStartUpAgg, ct8.CHData, ct8.CivLibData, ct8.ConCorData, ct8.EducExpDataPOST, ct8.EducExpDataUNESCO, ct8.EducExpAgg, ct8.FisPolData, ct8.FisPolAgg, ct8.FreedomInfoDataFreePress, ct8.FreedomInfoDataFOIA, ct8.FreedomInfoDataInterTools, ct8.FreedomInfoDataPolyNet, ct8.FreedomInfoAgg from (select isnull(t7.FreedomInfoCountryCode, ct7.country2) as country2, 
				isnull(t7.FreedomInfoYear, ct7.year) as year, t7.FreedomInfoDataFreePress, t7.FreedomInfoDataFOIA, t7.FreedomInfoDataInterTools, t7.FreedomInfoDataPolyNet, t7.FreedomInfoAgg, ct7.AccessCreditDataDepth, ct7.AccessCreditDataLegal, ct7.AccessCreditAgg, ct7.BusStartUpDataDays, ct7.BusStartUpDataCost, ct7.BusStartUpAgg, ct7.CHData, ct7.CivLibData, ct7.ConCorData, ct7.EducExpDataPOST, ct7.EducExpDataUNESCO, ct7.EducExpAgg, ct7.FisPolData, ct7.FisPolAgg from (select isnull(t6.FisPolCountryCode, ct6.country2) as country2, 
				isnull(t6.FisPolYear, ct6.year) as year, t6.FisPolData, t6.FisPolAgg, ct6.AccessCreditDataDepth, ct6.AccessCreditDataLegal, ct6.AccessCreditAgg, ct6.BusStartUpDataDays, ct6.BusStartUpDataCost, ct6.BusStartUpAgg, ct6.CHData, ct6.CivLibData, ct6.ConCorData, ct6.EducExpDataPOST, ct6.EducExpDataUNESCO, ct6.EducExpAgg from (select isnull(t5.EducExpCountryCode, ct5.country2) as country2, 
				isnull(t5.EducExpYear, ct5.year) as year, t5.EducExpDataPOST, t5.EducExpDataUNESCO, t5.EducExpAgg, ct5.AccessCreditDataDepth, ct5.AccessCreditDataLegal, ct5.AccessCreditAgg, ct5.BusStartUpDataDays, ct5.BusStartUpDataCost, ct5.BusStartUpAgg, ct5.CHData, ct5.CivLibData, ct5.ConCorData from (select isnull(t4.ConCorCountryCode, ct4.country2) as country2, 
				isnull(t4.ConCorYear, ct4.year) as year, t4.ConCorData, ct4.AccessCreditDataDepth, ct4.AccessCreditDataLegal, ct4.AccessCreditAgg, ct4.BusStartUpDataDays, ct4.BusStartUpDataCost, ct4.BusStartUpAgg, ct4.CHData, ct4.CivLibData from (select isnull(t3.CivLibCountryCode, ct3.country2) as country2, 
				isnull(t3.CivLibYear, ct3.year) as year, t3.CivLibData, ct3.AccessCreditDataDepth, ct3.AccessCreditDataLegal, ct3.AccessCreditAgg, ct3.BusStartUpDataDays, ct3.BusStartUpDataCost, ct3.BusStartUpAgg, ct3.CHData from (select isnull(t2.CHCountryCode, ct2.country2) as country2, 
				isnull(t2.CHYear, ct2.year) as year, t2.CHData, ct2.AccessCreditDataDepth, ct2.AccessCreditDataLegal, ct2.AccessCreditAgg, ct2.BusStartUpDataDays, ct2.BusStartUpDataCost, ct2.BusStartUpAgg from (select isnull(t1.BusStartUpCountryCode, ct1.country2) as country2, 
				isnull(t1.BusStartUpYear, ct1.year) as year, t1.BusStartUpDataDays, t1.BusStartUpDataCost, t1.BusStartUpAgg, ct1.AccessCreditDataDepth, ct1.AccessCreditDataLegal, ct1.AccessCreditAgg from (select t0.AccessCreditCountryCode as country2, 
				t0.AccessCreditYear as year, t0.AccessCreditDataDepth, t0.AccessCreditDataLegal, t0.AccessCreditAgg from dbo.t_AccessCredit t0 ) ct1 full outer join dbo.t_BusStartUp t1
		on ct1.country2=t1.BusStartUpCountryCode and ct1.year=t1.BusStartUpYear
		) ct2 full outer join dbo.t_ChiHealth t2
		on ct2.country2=t2.CHCountryCode and ct2.year=t2.CHYear
		) ct3 full outer join dbo.t_Civlib t3
		on ct3.country2=t3.CivLibCountryCode and ct3.year=t3.CivLibYear
		) ct4 full outer join dbo.t_ConCor t4
		on ct4.country2=t4.ConCorCountryCode and ct4.year=t4.ConCorYear
		) ct5 full outer join dbo.t_EducExp t5
		on ct5.country2=t5.EducExpCountryCode and ct5.year=t5.EducExpYear
		) ct6 full outer join dbo.t_FisPol t6
		on ct6.country2=t6.FisPolCountryCode and ct6.year=t6.FisPolYear
		) ct7 full outer join dbo.t_FreedomInfo t7
		on ct7.country2=t7.FreedomInfoCountryCode and ct7.year=t7.FreedomInfoYear
		) ct8 full outer join dbo.t_GenderEcon t8
		on ct8.country2=t8.GenderEconCountryCode and ct8.year=t8.GenderEconYear
		) ct9 full outer join dbo.t_GirlsPrim t9
		on ct9.country2=t9.GirlsPrimCountryCode and ct9.year=t9.GirlsPrimYear
		) ct10 full outer join dbo.t_GirlsSec t10
		on ct10.country2=t10.GirlsSecCountryCode and ct10.year=t10.GirlsSecYear
		) ct11 full outer join dbo.t_GovtEff t11
		on ct11.country2=t11.GovtEffCountryCode and ct11.year=t11.GovtEffYear
		) ct12 full outer join dbo.t_Health t12
		on ct12.country2=t12.HealthCountryCode and ct12.year=t12.HealthYear
		) ct13 full outer join dbo.t_Immun t13
		on ct13.country2=t13.ImmunCountryCode and ct13.year=t13.ImmunYear
		) ct14 full outer join dbo.t_Infl t14
		on ct14.country2=t14.InflCountryCode and ct14.year=t14.InflYear
		) ct15 full outer join dbo.t_LandRightsAccess t15
		on ct15.country2=t15.LRACountryCode and ct15.year=t15.LRAYear
		) ct16 full outer join dbo.t_NRM t16
		on ct16.country2=t16.NRMCountryCode and ct16.year=t16.NRMYear
		) ct17 full outer join dbo.t_PolRig t17
		on ct17.country2=t17.PolRigCountryCode and ct17.year=t17.PolRigYear
		) ct18 full outer join dbo.t_RegQuality t18
		on ct18.country2=t18.RegQualityCountryCode and ct18.year=t18.RegQualityYear
		) ct19 full outer join dbo.t_RuleLaw t19
		on ct19.country2=t19.RuleLawCountryCode and ct19.year=t19.RuleLawYear
		) ct20 full outer join dbo.t_TradePolicy t20
		on ct20.country2=t20.TradeCountryCode and ct20.year=t20.TradeYear
		) ct21 full outer join dbo.t_ChildMortality1 t21
		on ct21.country2=t21.CountryCode and ct21.year=t21.ChildMortalityYear
		) ct22 full outer join dbo.t_AccessSanitation1 t22
		on ct22.country2=t22.CountryCode and ct22.year=t22.AccessSanitationYear
		) ct23 full outer join dbo.t_AccessWater1 t23
		on ct23.country2=t23.CountryCode and ct23.year=t23.AccessWaterYear
		) as tt where tt.country2=countrycode2 and countrycode2!='--' and year>=1996
